Refactored Head out of Cache.
Separate the LRU cache from the code that tracks the current branch.  This is
the first step of a much bigger restructuring to allow me to manage separate
branches from the same MAWFS instance.

diff --git a/run_tests b/run_tests
--- a/run_tests
+++ b/run_tests
@@ -17,5 +17,8 @@
 root=$(dirname $0)
 for test in $root/test/*_test.crk; do
     echo -n "$test..."
-    crack $test
+    ~/w/crack/crack -l ~/w/crack/lib:lib $test || {
+        echo -e "$test \033[31mFAILED\033[0m"
+        exit 1
+    }
 done
